#!/bin/bash

# lognow v0.0.1
# Everyday log widget

startLog() {
	nvim ~/.Log.d/Log.$(date +%Y-%m-%d).md
}

if [ -d ~/.Log.d ]; then
	startLog
else
	git clone https://bitbucket.org/Ztalloc/.log.d.git ~/.Log.d
	startLog
fi
