#!/bin/bash

# lognow v0.0.2
# Everyday/topic log widget

TOPIC=${1:-}
startLog() {
	if [ "$TOPIC" != "" ]; then
		vim ~/.Log.d/$TOPIC.md
	else
		vim ~/.Log.d/Log.$(date +%Y-%m-%d).md
	fi
}

if [ -d ~/.Log.d ]; then
	startLog
fi
