#!/bin/sh

# git config --global http.proxy socks5://127.0.0.1:1080
git config --global http.proxy socks5h://127.0.0.1:9000
git config --global https.proxy socks5h://127.0.0.1:9000
export http_proxy="socks5://192.168.1.100:9000"
export https_proxy="socks5://192.168.1.100:9000"
export no_proxy="localhost,127.0.0.1,::1,.local"
